image: node:18 

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/  

build:
  stage: build
  script:
    - npm ci  
    - npm run build --configuration=production  
  artifacts:
    paths:
      - dist/ 

deploy:
  stage: deploy
  only:
    - main  
  before_script:
    - npm install -g firebase-tools 
  script:
    - firebase deploy --token "$FIREBASE_DEPLOY_TOKEN"  
